<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="#171914"><title>Brújula Brew</title>
  <link rel="manifest" href="/manifest.webmanifest"><link rel="stylesheet" href="/css/brew.css">
</head>
<body>
<header class="topbar">
  <a class="brand" href="#inicio"><span class="brandmark">B</span><span>BRÚJULA<br><small>BREW LOG</small></span></a>
  <nav class="desktop-nav" aria-label="Navegación principal">
    <a class="active" href="#inicio" data-nav="inicio">Inicio</a>
    <a href="#recetas" data-nav="recetas">Recetas</a>
    <a href="#lotes" data-nav="lotes">Cocciones</a>
    <a href="#calendario" data-nav="calendario">Agenda</a>
    <a href="#inventario" data-nav="inventario">Inventario</a>
    <a href="#herramientas" data-nav="herramientas">Herramientas</a>
  </nav>
  <button class="avatar" data-open="about">HB</button>
</header>

<main>
  @if(session('success'))<div class="toast">✓ {{ session('success') }}</div>@endif
  @if($errors->any())<div class="toast error">{{ $errors->first() }}</div>@endif

  <section id="inicio" class="page active">
    <div class="eyebrow">TU CERVECERÍA · {{ now()->translatedFormat('d M Y') }}</div>
    <div class="hero"><div><h1>¿Qué vamos a<br><em>crear hoy?</em></h1><p>Recetas, cocciones y cada detalle que hace única a tu cerveza.</p></div><div class="hop">✣</div></div>
    <div class="actions"><button class="primary" data-open="batch">＋ Nueva cocción</button><button class="secondary" data-open="recipe">Nueva receta</button></div>

    <div class="section-head"><div><span class="eyebrow">EN CURSO</span><h2>Ahora en bodega</h2></div><a href="#lotes" data-nav="lotes">Ver todos →</a></div>
    <div class="active-list">
      @forelse($active as $batch)
      <article class="batch-card" data-open="batch-{{ $batch->id }}">
        <div class="batch-top"><span class="status {{ $batch->status }}">{{ ['brewing'=>'Cocinando','fermenting'=>'Fermentando','conditioning'=>'Madurando'][$batch->status] }}</span><span>#{{ $batch->code }}</span></div>
        <h3>{{ $batch->recipe->name }}</h3><p>{{ $batch->recipe->style ?: 'Estilo libre' }}</p>
        <div class="metrics"><div><b>{{ $batch->temperature ?? '—' }}°</b><span>Temperatura</span></div><div><b>{{ $batch->og ?? '—' }}</b><span>Densidad inicial</span></div><div><b>{{ $batch->brewed_at->diffInDays(now()) }}</b><span>Días</span></div></div>
        <div class="progress"><i style="width:{{ min(100, $batch->brewed_at->diffInDays(now()) * 7) }}%"></i></div>
      </article>
      @empty <div class="empty"><span>◌</span><h3>La bodega está esperando</h3><p>Elegí una receta y registrá tu primera cocción.</p></div>
      @endforelse
    </div>
    <div class="stats"><div><b>{{ $recipes->count() }}</b><span>Recetas</span></div><div><b>{{ $batches->count() }}</b><span>Cocciones</span></div><div><b>{{ $batches->where('status','finished')->count() }}</b><span>Terminadas</span></div></div>
  </section>

  <section id="recetas" class="page">
    <div class="page-title"><div><span class="eyebrow">TU LIBRO</span><h1>Recetas</h1></div><button class="round" data-open="recipe">＋</button></div>
    <div class="recipe-grid">
      @forelse($recipes as $recipe)<article class="recipe-card"><div class="recipe-color" style="--beer:{{ $recipe->color ?: '#d99026' }}"></div><div><span>{{ $recipe->style ?: 'Estilo libre' }}</span><div class="recipe-heading"><h3>{{ $recipe->name }}</h3><button type="button" class="edit-button" data-open="recipe-{{ $recipe->id }}" aria-label="Editar {{ $recipe->name }}">✎ Editar receta</button></div><p>{{ $recipe->batch_size }} L · {{ $recipe->abv ?: '—' }}% ABV · {{ $recipe->ibu ?: '—' }} IBU</p><footer><b>{{ $recipe->batches_count }}</b> cocciones <button data-open="batch" data-recipe="{{ $recipe->id }}">Cocinar →</button></footer></div></article>
      @empty <div class="empty"><h3>Todavía no hay recetas</h3><p>Guardá ingredientes, objetivos y proceso para repetir tus mejores cervezas.</p></div>@endforelse
    </div>
  </section>

  <section id="lotes" class="page">
    <div class="page-title"><div><span class="eyebrow">BITÁCORA</span><h1>Cocciones</h1></div><button class="round" data-open="batch">＋</button></div>
    @forelse($batches as $batch)<article class="log-row" data-open="batch-{{ $batch->id }}"><time>{{ $batch->brewed_at->format('d') }}<small>{{ strtoupper($batch->brewed_at->translatedFormat('M')) }}</small></time><div><span class="status {{ $batch->status }}">{{ ucfirst($batch->status) }}</span><h3>{{ $batch->recipe->name }}</h3><p>#{{ $batch->code }} · {{ $batch->volume ?: '—' }} L · OG {{ $batch->og ?: '—' }}</p></div><strong>›</strong></article>
    @empty <div class="empty"><h3>Tu bitácora está vacía</h3><p>Cada cocción queda ligada a su receta, pero conserva sus parámetros reales.</p></div>@endforelse
  </section>
  <section id="calendario" class="page">
    <div class="page-title"><div><span class="eyebrow">PRÓXIMOS PASOS</span><h1>Agenda cervecera</h1></div><button class="round" data-open="reminder">＋</button></div>
    <div class="agenda-summary"><b>{{ $reminders->where('completed',false)->count() }}</b><span>tareas pendientes</span><i></i><b>{{ $reminders->where('completed',false)->filter(fn($r)=>$r->due_at->isPast())->count() }}</b><span>vencidas</span></div>
    <div class="agenda-list">@forelse($reminders as $reminder)<article class="{{ $reminder->completed?'done':($reminder->due_at->isPast()?'overdue':'') }}"><form method="post" action="{{ route('reminders.toggle',$reminder) }}">@csrf @method('PATCH')<button title="Marcar como completada">{{ $reminder->completed?'✓':'○' }}</button></form><time>{{ $reminder->due_at->translatedFormat('d M') }}<small>{{ $reminder->due_at->format('H:i') }}</small></time><div><h3>{{ $reminder->title }}</h3><p>{{ $reminder->batch?->recipe?->name }} {{ $reminder->batch?'· #'.$reminder->batch->code:'' }} {{ $reminder->notes?'· '.$reminder->notes:'' }}</p></div></article>@empty<div class="empty"><h3>Sin tareas programadas</h3><p>Agendá dry hop, mediciones, cold crash, envasado o cata.</p></div>@endforelse</div>
  </section>

  <section id="inventario" class="page">
    <div class="page-title"><div><span class="eyebrow">INSUMOS</span><h1>Inventario</h1></div><button class="round" data-open="inventory-item">＋</button></div>
    <div class="stock-summary"><div><b>{{ $inventory->count() }}</b><span>Insumos</span></div><div><b>{{ $inventory->filter->low_stock->count() }}</b><span>Stock bajo</span></div><div><b>{{ $inventory->filter(fn($i)=>$i->expires_at && $i->expires_at->lte(now()->addDays(30)))->count() }}</b><span>Por vencer</span></div></div>
    <div class="inventory-grid">@forelse($inventory as $item)<article class="{{ $item->low_stock?'low-stock':'' }}"><div><span>{{ ['malt'=>'Malta','hop'=>'Lúpulo','yeast'=>'Levadura','water'=>'Agua / sal','adjunct'=>'Adjunto','clarifier'=>'Clarificante','packaging'=>'Envase','other'=>'Otro'][$item->category] }}</span>@if($item->low_stock)<em>STOCK BAJO</em>@endif<h3>{{ $item->name }}</h3><p>Lote {{ $item->lot?:'—' }} · Vence {{ $item->expires_at?->format('d/m/Y')?:'—' }}</p></div><strong>{{ $item->quantity }} <small>{{ $item->unit }}</small></strong><form method="post" action="{{ route('inventory.adjust',$item) }}">@csrf @method('PATCH')<input type="number" step=".01" min="0.01" name="amount" placeholder="Cantidad" required><button name="operation" value="use">− Usar</button><button name="operation" value="add">＋ Agregar</button></form></article>@empty<div class="empty"><h3>Tu depósito está vacío</h3><p>Cargá maltas, lúpulos, levaduras, sales y material de envasado.</p></div>@endforelse</div>
  </section>

  <section id="herramientas" class="page">
    <div class="page-title"><div><span class="eyebrow">CÁLCULOS RÁPIDOS</span><h1>Herramientas</h1></div></div>
    <div class="tool-grid">
      <article class="calc"><span>01</span><h2>Alcohol y atenuación</h2><div class="form-grid"><label>OG<input id="calc-og" type="number" step=".001" value="1.050"></label><label>FG<input id="calc-fg" type="number" step=".001" value="1.010"></label></div><output id="abv-result">5.3% ABV · 80% atenuación</output></article>
      <article class="calc"><span>02</span><h2>Corrección de densidad</h2><div class="form-grid"><label>Lectura SG<input id="corr-sg" type="number" step=".001" value="1.050"></label><label>Temperatura °C<input id="corr-temp" type="number" step=".1" value="25"></label></div><output id="corr-result">1.051 SG corregida a 20 °C</output></article>
      <article class="calc"><span>03</span><h2>Azúcar de priming</h2><div class="form-grid"><label>Litros<input id="prime-liters" type="number" step=".1" value="20"></label><label>CO₂ objetivo<input id="prime-co2" type="number" step=".1" value="2.4"></label><label>Temp. máxima °C<input id="prime-temp" type="number" step=".1" value="20"></label><label>Azúcar<select id="prime-type"><option value="1">Dextrosa</option><option value="1.1">Sacarosa</option></select></label></div><output id="prime-result">— g de azúcar</output></article>
      <article class="calc"><span>04</span><h2>Eficiencia</h2><div class="form-grid"><label>Litros de mosto<input id="eff-liters" type="number" step=".1" value="20"></label><label>OG<input id="eff-og" type="number" step=".001" value="1.050"></label><label class="wide">Potencial total de granos (puntos·L)<input id="eff-potential" type="number" value="1400"></label></div><output id="eff-result">—% eficiencia</output></article>
    </div>
    <div class="module-links"><button data-nav="calendario">Abrir agenda</button><button data-nav="inventario">Abrir inventario</button></div>
  </section>
</main>

<nav class="bottom-nav"><a class="active" href="#inicio" data-nav="inicio"><span>⌂</span>Inicio</a><a href="#recetas" data-nav="recetas"><span>◇</span>Recetas</a><button data-open="batch">＋</button><a href="#lotes" data-nav="lotes"><span>≋</span>Cocciones</a><a href="#herramientas" data-nav="herramientas"><span>⌘</span>Más</a></nav>

<dialog id="recipe"><form method="post" action="{{ route('recipes.store') }}">@csrf <header><div><span class="eyebrow">NUEVA</span><h2>Receta</h2></div><button type="button" data-close>×</button></header><div class="form-grid"><label class="wide">Nombre<input name="name" required placeholder="Ej. IPA del patio"></label><label class="wide">Estilo<input name="style" placeholder="American IPA"></label><label>Litros<input type="number" step=".1" name="batch_size" value="20" required></label><label>Color<input type="color" name="color" value="#d99026"></label><label>OG objetivo<input type="number" step=".001" name="og" placeholder="1.058"></label><label>FG objetivo<input type="number" step=".001" name="fg" placeholder="1.012"></label><label>ABV %<input type="number" step=".1" name="abv"></label><label>IBU<input type="number" name="ibu"></label><label>Eficiencia %<input type="number" step=".1" name="efficiency" placeholder="72"></label><label>pH macerado<input type="number" step=".01" name="mash_ph" placeholder="5.30"></label><label class="wide">Ingredientes<textarea name="ingredients" rows="5" placeholder="Maltas en kg, lúpulos en g y minuto, levadura, adjuntos..."></textarea></label><label class="wide">Agua y sales<textarea name="water_profile" rows="3" placeholder="Litros de macerado/lavado, Ca, Mg, Na, Cl, SO4, HCO3 y sales agregadas"></textarea></label><label class="wide">Plan de macerado<textarea name="mash_schedule" rows="3" placeholder="Escalones: temperatura, minutos, relación agua/grano y mash out"></textarea></label><label class="wide">Hervido y adiciones<textarea name="boil_plan" rows="3" placeholder="Duración, lúpulos por minuto, nutrientes, clarificante y whirlpool"></textarea></label><label class="wide">Fermentación<textarea name="fermentation_plan" rows="3" placeholder="Levadura, cantidad, oxigenación, temperaturas, descanso de diacetilo y días"></textarea></label><label class="wide">Maduración y clarificado<textarea name="clarification_plan" rows="2" placeholder="Cold crash, gelatina/biofine, trasiegos y tiempos"></textarea></label><label class="wide">Envasado y carbonatación<textarea name="packaging_plan" rows="2" placeholder="Botella o barril, volúmenes de CO₂, azúcar de priming y guarda"></textarea></label><label class="wide">Proceso general<textarea name="process" rows="3"></textarea></label><label class="wide">Notas<textarea name="notes" rows="2"></textarea></label></div><button class="primary wide-btn">Guardar receta</button></form></dialog>

@foreach($recipes as $recipe)
<dialog id="recipe-{{ $recipe->id }}"><div class="detail">
  <form method="post" action="{{ route('recipes.update', $recipe) }}" class="edit-recipe">@csrf @method('PATCH')
    <header><div><span class="eyebrow">EDITAR RECETA</span><h2>{{ $recipe->name }}</h2></div><button type="button" data-close>×</button></header>
    <div class="form-grid">
      <label class="wide">Nombre<input name="name" required value="{{ $recipe->name }}"></label><label class="wide">Estilo<input name="style" value="{{ $recipe->style }}"></label>
      <label>Litros<input type="number" step=".1" name="batch_size" value="{{ $recipe->batch_size }}" required></label><label>Color<input type="color" name="color" value="{{ $recipe->color ?: '#d99026' }}"></label>
      <label>OG objetivo<input type="number" step=".001" name="og" value="{{ $recipe->og }}"></label><label>FG objetivo<input type="number" step=".001" name="fg" value="{{ $recipe->fg }}"></label>
      <label>ABV %<input type="number" step=".1" name="abv" value="{{ $recipe->abv }}"></label><label>IBU<input type="number" name="ibu" value="{{ $recipe->ibu }}"></label><label>Eficiencia %<input type="number" step=".1" name="efficiency" value="{{ $recipe->efficiency }}"></label><label>pH macerado<input type="number" step=".01" name="mash_ph" value="{{ $recipe->mash_ph }}"></label>
      <label class="wide">Ingredientes<textarea name="ingredients" rows="5">{{ $recipe->ingredients }}</textarea></label><label class="wide">Agua y sales<textarea name="water_profile" rows="3">{{ $recipe->water_profile }}</textarea></label><label class="wide">Plan de macerado<textarea name="mash_schedule" rows="3">{{ $recipe->mash_schedule }}</textarea></label><label class="wide">Hervido y adiciones<textarea name="boil_plan" rows="3">{{ $recipe->boil_plan }}</textarea></label><label class="wide">Fermentación<textarea name="fermentation_plan" rows="3">{{ $recipe->fermentation_plan }}</textarea></label><label class="wide">Maduración y clarificado<textarea name="clarification_plan" rows="2">{{ $recipe->clarification_plan }}</textarea></label><label class="wide">Envasado y carbonatación<textarea name="packaging_plan" rows="2">{{ $recipe->packaging_plan }}</textarea></label><label class="wide">Proceso general<textarea name="process" rows="3">{{ $recipe->process }}</textarea></label><label class="wide">Notas<textarea name="notes" rows="2">{{ $recipe->notes }}</textarea></label>
    </div><button class="primary wide-btn">Guardar cambios</button>
  </form>
  <div class="danger-zone"><div><b>Eliminar receta</b><p>También eliminará sus {{ $recipe->batches_count }} cocciones y todas sus mediciones.</p></div><form method="post" action="{{ route('recipes.destroy', $recipe) }}" data-delete-recipe="{{ $recipe->name }}">@csrf @method('DELETE')<button class="danger" type="submit">Eliminar</button></form></div>
</div></dialog>
@endforeach

<dialog id="batch"><form method="post" action="{{ route('batches.store') }}">@csrf <header><div><span class="eyebrow">NUEVA</span><h2>Cocción</h2></div><button type="button" data-close>×</button></header><div class="form-grid"><label class="wide">Receta<select name="recipe_id" required><option value="">Elegir receta…</option>@foreach($recipes as $r)<option value="{{ $r->id }}">{{ $r->name }}</option>@endforeach</select></label><label>Código<input name="code" required value="L{{ str_pad($batches->count()+1, 3, '0', STR_PAD_LEFT) }}"></label><label>Fecha<input type="date" name="brewed_at" value="{{ now()->format('Y-m-d') }}" required></label><label>Estado<select name="status"><option value="planned">Planificada</option><option value="brewing">Cocinando</option><option value="fermenting">Fermentando</option><option value="conditioning">Madurando</option></select></label><label>Volumen al fermentador (L)<input type="number" step=".1" name="volume"></label><label>OG real<input type="number" step=".001" name="og"></label><label>Volumen pre-hervor (L)<input type="number" step=".1" name="pre_boil_volume"></label><label>Densidad pre-hervor<input type="number" step=".001" name="pre_boil_gravity"></label><label>Volumen post-hervor (L)<input type="number" step=".1" name="post_boil_volume"></label><label>Temp. inoculación °C<input type="number" step=".1" name="pitch_temperature"></label><label class="wide">Levadura / lote / cantidad<input name="yeast" placeholder="Ej. US-05 lote 123 · 11,5 g"></label><label>Temperatura actual °C<input type="number" step=".1" name="temperature"></label><label class="wide">Notas del día<textarea name="notes" rows="4" placeholder="Clima, molienda, problemas, aromas, decisiones..."></textarea></label></div><button class="primary wide-btn" @disabled($recipes->isEmpty())>Registrar cocción</button>@if($recipes->isEmpty())<p class="hint">Primero necesitás crear una receta.</p>@endif</form></dialog>

@foreach($batches as $batch)<dialog id="batch-{{ $batch->id }}"><div class="detail"><header><div><span class="eyebrow">#{{ $batch->code }}</span><h2>{{ $batch->recipe->name }}</h2></div><button type="button" data-close>×</button></header><div class="detail-metrics"><div><b>{{ $batch->og ?: '—' }}</b><span>OG</span></div><div><b>{{ $batch->fg ?: '—' }}</b><span>FG</span></div><div><b>{{ $batch->abv ?? '—' }}%</b><span>ABV real</span></div></div><form method="post" action="{{ route('readings.store',$batch) }}" class="reading">@csrf<h3>Nueva medición</h3><div class="form-grid"><label>Fecha y hora<input type="datetime-local" name="measured_at" value="{{ now()->format('Y-m-d\TH:i') }}" required></label><label>Densidad<input type="number" step=".001" name="gravity"></label><label>Temperatura °C<input type="number" step=".1" name="temperature"></label><label>pH<input type="number" step=".01" name="ph"></label><label class="wide">Observación<input name="notes" placeholder="Aroma, actividad, cambios..."></label></div><button class="secondary wide-btn">Anotar medición</button></form><div class="timeline">@forelse($batch->readings as $reading)<div><i></i><span>{{ $reading->measured_at->format('d/m H:i') }}</span><b>{{ $reading->gravity ?: '—' }} SG · {{ $reading->temperature ?: '—' }}°C</b><p>{{ $reading->notes }}</p></div>@empty<p class="hint">Aún no hay mediciones.</p>@endforelse</div><form method="post" action="{{ route('batches.update',$batch) }}">@csrf @method('PATCH')<h3>Actualizar lote</h3><div class="form-grid"><label>Estado<select name="status">@foreach(['planned'=>'Planificada','brewing'=>'Cocinando','fermenting'=>'Fermentando','conditioning'=>'Madurando','packaged'=>'Envasada','finished'=>'Terminada'] as $v=>$l)<option value="{{ $v }}" @selected($batch->status===$v)>{{ $l }}</option>@endforeach</select></label><label>FG real<input type="number" step=".001" name="fg" value="{{ $batch->fg }}"></label><label>Temperatura<input type="number" step=".1" name="temperature" value="{{ $batch->temperature }}"></label><label>Valoración 1–5<input type="number" min="1" max="5" name="rating" value="{{ $batch->rating }}"></label><label class="wide">Notas<input name="notes" value="{{ $batch->notes }}"></label></div><button class="primary wide-btn">Guardar cambios</button></form></div></dialog>@endforeach
<dialog id="reminder"><form method="post" action="{{ route('reminders.store') }}">@csrf<header><div><span class="eyebrow">NUEVA TAREA</span><h2>Programar recordatorio</h2></div><button type="button" data-close>×</button></header><div class="form-grid"><label class="wide">Lote (opcional)<select name="batch_id"><option value="">Tarea general</option>@foreach($batches as $batch)<option value="{{ $batch->id }}">#{{ $batch->code }} · {{ $batch->recipe->name }}</option>@endforeach</select></label><label class="wide">Tarea<input name="title" required placeholder="Ej. Agregar dry hop"></label><label>Fecha y hora<input type="datetime-local" name="due_at" required></label><label>Notas<input name="notes" placeholder="Cantidad, temperatura..."></label></div><button class="primary wide-btn">Guardar recordatorio</button></form></dialog>
<dialog id="inventory-item"><form method="post" action="{{ route('inventory.store') }}">@csrf<header><div><span class="eyebrow">NUEVO INSUMO</span><h2>Agregar al inventario</h2></div><button type="button" data-close>×</button></header><div class="form-grid"><label class="wide">Nombre<input name="name" required placeholder="Ej. Citra 2025"></label><label>Categoría<select name="category"><option value="malt">Malta</option><option value="hop">Lúpulo</option><option value="yeast">Levadura</option><option value="water">Agua / sal</option><option value="adjunct">Adjunto</option><option value="clarifier">Clarificante</option><option value="packaging">Envase</option><option value="other">Otro</option></select></label><label>Unidad<select name="unit"><option>kg</option><option>g</option><option>L</option><option>ml</option><option>unidad</option><option>sobre</option></select></label><label>Cantidad<input type="number" step=".01" name="quantity" required></label><label>Stock mínimo<input type="number" step=".01" name="minimum_stock"></label><label>Lote<input name="lot"></label><label>Vencimiento<input type="date" name="expires_at"></label><label class="wide">Notas<input name="notes"></label></div><button class="primary wide-btn">Agregar insumo</button></form></dialog>
@foreach($batches as $batch)
<dialog id="journal-{{ $batch->id }}"><div class="detail journal-dialog"><header><div><span class="eyebrow">#{{ $batch->code }} · PROCESO COMPLETO</span><h2>Bitácora de elaboración</h2><p>{{ $batch->recipe->name }}</p></div><button type="button" data-close>×</button></header>
<div class="comparison"><div><span>OG objetivo / real</span><b>{{ $batch->recipe->og?:'—' }} <i>→</i> {{ $batch->og?:'—' }}</b><small>@if($batch->og && $batch->recipe->og){{ sprintf('%+.3f',$batch->og-$batch->recipe->og) }} diferencia @endif</small></div><div><span>FG objetivo / real</span><b>{{ $batch->recipe->fg?:'—' }} <i>→</i> {{ $batch->fg?:'—' }}</b><small>@if($batch->fg && $batch->recipe->fg){{ sprintf('%+.3f',$batch->fg-$batch->recipe->fg) }} diferencia @endif</small></div><div><span>Volumen objetivo / real</span><b>{{ $batch->recipe->batch_size }} <i>→</i> {{ $batch->volume?:'—' }} L</b><small>@if($batch->volume){{ sprintf('%+.1f',$batch->volume-$batch->recipe->batch_size) }} L diferencia @endif</small></div><div><span>ABV objetivo / real</span><b>{{ $batch->recipe->abv?:'—' }} <i>→</i> {{ $batch->abv?:'—' }}%</b><small>@if($batch->abv && $batch->recipe->abv){{ sprintf('%+.1f',$batch->abv-$batch->recipe->abv) }} puntos @endif</small></div></div>
<div class="chart-box"><div><span class="eyebrow">FERMENTACIÓN</span><h3>Densidad y temperatura</h3></div><canvas class="fermentation-chart" height="210"></canvas><script type="application/json" class="chart-data">{!! json_encode($batch->readings->sortBy('measured_at')->map(fn($r)=>['date'=>$r->measured_at->format('d/m'),'gravity'=>$r->gravity?floatval($r->gravity):null,'temperature'=>$r->temperature?floatval($r->temperature):null])->values()) !!}</script>@if($batch->readings->count()<2)<p class="hint">Cargá al menos dos mediciones para trazar la curva.</p>@endif</div>
<form method="post" action="{{ route('logs.store',$batch) }}" class="process-form">@csrf<div class="form-grid"><label>Etapa<select name="stage" required><option value="water">Agua y sales</option><option value="milling">Molienda</option><option value="mash">Macerado</option><option value="sparge">Lavado</option><option value="boil">Hervido / adición</option><option value="chill">Enfriado / trasiego</option><option value="fermentation">Fermentación</option><option value="conditioning">Maduración</option><option value="clarification">Clarificado</option><option value="packaging">Envasado</option><option value="tasting">Cata</option></select></label><label>Fecha y hora<input type="datetime-local" name="occurred_at" value="{{ now()->format('Y-m-d\TH:i') }}" required></label><label class="wide">Evento o acción<input name="title" required placeholder="Ej. Descanso a 67 °C, adición Cascade, cold crash..."></label><label>Temperatura °C<input type="number" step=".1" name="temperature"></label><label>Densidad SG<input type="number" step=".001" name="gravity"></label><label>pH<input type="number" step=".01" name="ph"></label><label>Duración (min)<input type="number" name="duration"></label><label>Valor<input type="number" step=".01" name="value"></label><label>Unidad<input name="unit" placeholder="g, L, ml, psi..."></label><label class="wide">Observaciones<input name="notes" placeholder="Aspecto, aroma, desvíos y correcciones"></label></div><button class="secondary wide-btn">＋ Registrar evento</button></form>
<div class="stage-list">@forelse($batch->logs as $log)<article><div><span class="stage-tag">{{ ['water'=>'Agua','milling'=>'Molienda','mash'=>'Macerado','sparge'=>'Lavado','boil'=>'Hervido','chill'=>'Enfriado','fermentation'=>'Fermentación','conditioning'=>'Maduración','clarification'=>'Clarificado','packaging'=>'Envasado','tasting'=>'Cata'][$log->stage] }}</span><time>{{ $log->occurred_at->format('d/m H:i') }}</time></div><h4>{{ $log->title }}</h4><p>@if($log->temperature !== null){{ $log->temperature }}°C · @endif @if($log->gravity !== null)SG {{ $log->gravity }} · @endif @if($log->ph !== null)pH {{ $log->ph }} · @endif @if($log->duration){{ $log->duration }} min · @endif @if($log->value !== null){{ $log->value }} {{ $log->unit }}@endif</p>@if($log->notes)<small>{{ $log->notes }}</small>@endif</article>@empty<p class="hint">Todavía no hay eventos. Anotá cada medición, adición, cambio de temperatura o decisión.</p>@endforelse</div></div></dialog>
@endforeach
<dialog id="about"><div class="detail"><header><div><span class="eyebrow">BRÚJULA</span><h2>Tu cerveza, mejor documentada</h2></div><button data-close>×</button></header><p>Los datos viven en esta instalación. Para agregarla al celular, abrí el menú del navegador y elegí “Agregar a pantalla de inicio”.</p><button id="install" class="primary wide-btn" hidden>Instalar aplicación</button></div></dialog>
<script src="/js/brew.js"></script>
</body></html>
